---
# Core declib options

# log_path: ~/.config/example-app/example-app.log
# log_level: INFO
# stderr_log_level: WARNING


# Specific to example app

# stuff: things
# spam: eggs
# place: ~/tmp/blah
